### ISSUE TITLE
The Search Result result

### ISSUE THREAD

**Issue by andyduong1920** [hanam1ni/google-crawler#15]
Should we display the search result as a web page instead of the raw HTML content @hanam1ni 🤔

![image](https://user-images.githubusercontent.com/11751745/99237791-8d0bd600-282b-11eb-87d5-23d527631821.png)

**Comment by hanam1ni** [comment]
Sound good. I will note that as improvement and create a story for that 👍

**Comment by hanam1ni** [comment]
Added in `0.3.1` 🎉
