### ISSUE TITLE
CSV uploads triggers an internal server erro

### ISSUE THREAD

**Issue by olivierobert** [hanam1ni/google-crawler#32]
# Environment

- Platform: web desktop
- Version: latest
- Environment: production (https://google-result-crawler.herokuapp.com/)

# Steps to Reproduce

1. Go to https://google-result-crawler.herokuapp.com/keyword/new
2. Upload a CSV with the following format

```
rails,ruby,developer job
```

All words are in one line separated by commas

# Expected

The user should be redirected to the keyword details page:

![image](https://user-images.githubusercontent.com/696529/103062135-efe94d80-45df-11eb-95c6-609b73314ddb.png)

# Actual

![Screen Shot 2563-12-24 at 11 57 36](https://user-images.githubusercontent.com/696529/103062102-d2b47f00-45df-11eb-9939-e045bd38b88a.png)

**Comment by hanam1ni** [comment]
Fixed in 0.3.2 🎉

**Comment by hanam1ni** [comment]
Fixed in 0.3.2 🎉
