### ISSUE TITLE
Application does not handle adding the same keyword twice

### ISSUE THREAD

**Issue by olivierobert** [hanam1ni/google-crawler#33]
# Environment

- Platform: web desktop
- Version: latest
- Environment: production (https://google-result-crawler.herokuapp.com/)

# Steps to Reproduce

1. Go to https://google-result-crawler.herokuapp.com/keyword/new
2. Use the form to add a single keyword. This will trigger the search.
3. Now go again to https://google-result-crawler.herokuapp.com/keyword/new and add the same keyword

# Expected

Several options:

- Show an error that this user has been added -> bad UX
- Do a new form for the same keyword -> okay UX
- Store multiple results for the same keyword so that it's possible to track any changes through time -> hard to implement

# Actual

The user is redirected to the page to add a keyword without any message:

![2563-12-24 12 10 37](https://user-images.githubusercontent.com/696529/103062557-1b206c80-45e1-11eb-90b4-d39ce07acccb.gif)

**Comment by hanam1ni** [comment]
Fixed in 0.3.2 🎉
